let
  Origen = Excel.Workbook(Web.Contents("https://finansustentable-my.sharepoint.com/personal/bc_gael_finsus_mx/Documents/Documentos/AUTO-Cobranza/Copia%20de%20Reportes%20IA.xlsx"), null, true),
  #"Navegación 1" = Origen{[Item = "TablaJudicial", Kind = "Table"]}[Data],
  #"Consultas combinadas" = Table.NestedJoin(#"Navegación 1", {"Referencia Externa"}, TablaF1, {"Referencia Externa"}, "TablaF1", JoinKind.LeftOuter),
  #"TablaF1 expandido" = Table.ExpandTableColumn(#"Consultas combinadas", "TablaF1", {"Total Vencido", "Último Pago", "Monto Pago", "Saldo Mora", "Saldo Capital Total", "Adeudo Total", "Días Mora", "Bucket"}, {"Total Vencido.1", "Último Pago", "Monto Pago", "Saldo Mora.1", "Saldo Capital Total.1", "Adeudo Total.1", "Días Mora.1", "Bucket.1"}),
  #"Columnas reordenadas" = Table.ReorderColumns(#"TablaF1 expandido", {"Asignado", "0", "Referencia Externa", "cliente", "Inicio", "Plazo", "# de mensualidad", "Referencia bancomer", "Interbancaria finsus", "Mora a la asignacion ", "Mora a agosto", "Cuota mensual#(lf)dia 05", "Total Vencido", "saldo mora", "Saldo Capital Total", "Adeudo Total", "Días Mora", "Bucket", "pagos oct", "monto cubierto ", "comentarios Finsus", "gestion telefonica ", "gestion en campo ", "Dirección negocio y/o fiscal", "telefono", "Dueño", "Dirección ", " Telefono ", "parentesco 1", "nombre ", "telefono ", "parentesco 2", "nombre 2", "telefono 3", "parentesco 3 ", "nombre 4", "telefono 5", "parentesco 4 ", "nombre 6", "telefono 7", "parentesco 5", "nombre 8", "telefono 9", "parentesco 6", "nombre 10", "telefono 11", "parentesco 7", "nombre 12", "telefono 13", "Total Vencido.1", "Saldo Mora.1", "Saldo Capital Total.1", "Adeudo Total.1", "Días Mora.1", "Bucket.1", "Último Pago", "Monto Pago"}),
  #"Columnas quitadas" = Table.RemoveColumns(#"Columnas reordenadas", {"Total Vencido", "saldo mora", "Saldo Capital Total", "Adeudo Total", "Días Mora", "Bucket", "pagos oct", "monto cubierto "}),
  #"Columnas reordenadas 1" = Table.ReorderColumns(#"Columnas quitadas", {"Asignado", "0", "Referencia Externa", "cliente", "Inicio", "Plazo", "# de mensualidad", "Referencia bancomer", "Interbancaria finsus", "Mora a la asignacion ", "Mora a agosto", "Cuota mensual#(lf)dia 05", "Total Vencido.1", "Saldo Mora.1", "Saldo Capital Total.1", "Adeudo Total.1", "Días Mora.1", "Bucket.1", "Último Pago", "Monto Pago", "comentarios Finsus", "gestion telefonica ", "gestion en campo ", "Dirección negocio y/o fiscal", "telefono", "Dueño", "Dirección ", " Telefono ", "parentesco 1", "nombre ", "telefono ", "parentesco 2", "nombre 2", "telefono 3", "parentesco 3 ", "nombre 4", "telefono 5", "parentesco 4 ", "nombre 6", "telefono 7", "parentesco 5", "nombre 8", "telefono 9", "parentesco 6", "nombre 10", "telefono 11", "parentesco 7", "nombre 12", "telefono 13"}),
  #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas 1", {{"Total Vencido.1", "Exigible este mes"}, {"Saldo Mora.1", "Saldo Mora"}, {"Saldo Capital Total.1", "Saldo Capital Total"}, {"Adeudo Total.1", "Adeudo Total"}, {"Días Mora.1", "Días Mora"}, {"Bucket.1", "Bucket"}, {"Último Pago", "Pagos este mes"}}),
  #"Personalizado agregado" = Table.AddColumn(#"Columnas con nombre cambiado", "Temp_Pagos", each if Date.Month([Pagos este mes]) = Date.Month(DateTime.LocalNow()) 
   and Date.Year([Pagos este mes]) = Date.Year(DateTime.LocalNow())
then [Pagos este mes] 
else null),
  #"Columnas quitadas 1" = Table.RemoveColumns(#"Personalizado agregado", {"Pagos este mes"}),
  #"Columnas con nombre cambiado 1" = Table.RenameColumns(#"Columnas quitadas 1", {{"Temp_Pagos", "Pagos este mes"}}),
  #"Personalizado agregado 1" = Table.AddColumn(#"Columnas con nombre cambiado 1", "Temp_Monto", each if Date.Month([Pagos este mes]) = Date.Month(DateTime.LocalNow()) 
   and Date.Year([Pagos este mes]) = Date.Year(DateTime.LocalNow())
then [Monto Pago]
else null),
  #"Columnas quitadas 2" = Table.RemoveColumns(#"Personalizado agregado 1", {"Monto Pago"}),
  #"Columnas con nombre cambiado 2" = Table.RenameColumns(#"Columnas quitadas 2", {{"Temp_Monto", "Monto cubierto"}}),
  #"Columnas reordenadas 2" = Table.ReorderColumns(#"Columnas con nombre cambiado 2", {"Asignado", "0", "Referencia Externa", "cliente", "Inicio", "Plazo", "# de mensualidad", "Referencia bancomer", "Interbancaria finsus", "Mora a la asignacion ", "Mora a agosto", "Cuota mensual#(lf)dia 05", "Exigible este mes", "Saldo Mora", "Saldo Capital Total", "Adeudo Total", "Días Mora", "Bucket", "Pagos este mes", "Monto cubierto", "comentarios Finsus", "gestion telefonica ", "gestion en campo ", "Dirección negocio y/o fiscal", "telefono", "Dueño", "Dirección ", " Telefono ", "parentesco 1", "nombre ", "telefono ", "parentesco 2", "nombre 2", "telefono 3", "parentesco 3 ", "nombre 4", "telefono 5", "parentesco 4 ", "nombre 6", "telefono 7", "parentesco 5", "nombre 8", "telefono 9", "parentesco 6", "nombre 10", "telefono 11", "parentesco 7", "nombre 12", "telefono 13"}),
  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Columnas reordenadas 2", {{"Exigible este mes", Currency.Type}, {"Saldo Mora", Currency.Type}, {"Saldo Capital Total", Currency.Type}, {"Adeudo Total", Currency.Type}, {"Pagos este mes", type date}, {"Monto cubierto", Currency.Type}}),
  #"Columnas con nombre cambiado 3" = Table.RenameColumns(#"Tipo de columna cambiado", {{"Exigible este mes", "Total vencido"}})
in
  #"Columnas con nombre cambiado 3"